export const service = {
  ADD_SERVICE_REQUEST: 'ADD_SERVICE_REQUEST',
  ADD_SERVICE_SUCCESS: 'ADD_SERVICE_SUCCESS',
  REMOVE_SERVICE_REQUEST: 'REMOVE_SERVICE_REQUEST',
  REMOVE_SERVICE_SUCCESS: 'REMOVE_SERVICE_SUCCESS',
  GET_SERVICES: 'GET_SERVICES',
  INITIALIZE_SERVICES: 'INITIALIZE_SERVICES',
}

export const serviceRequest = {
  DECLINE_REQUEST: 'DECLINE_REQUEST',
  ACCEPT_REQUEST: 'ACCEPT_REQUEST'
}

export const auth = {
  SIGN_UP_REQUESTED: 'SIGN_UP_REQUESTED',
  SIGN_IN: 'SIGN_IN',
  SIGN_IN_REQUEST: 'SIGNIN_REQUEST',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',
  SIGN_OUT: 'SING_OUT',
  SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
  RESTORE_TOKEN: 'RESTORE_TOKEN',
  RESTORE_TOKEN_REQUEST: 'RESTORE_TOKEN_REQUEST',
  RESTORE_TOKEN_SUCCESS: 'RESTORE_TOKEN_SUCCESS',
  RESTORE_TOKEN_FAILURE: 'RESTORE_TOKEN_FAILURE',
}

export const user = {
  RESTORE_USER_DETAILS: ' RESTORE_USER_DETAILS',
  USER_PARTIAL_UPDATE_REQUEST: 'USER_PARTIAL_UPDATE_REQUEST',
  USER_PARTIAL_UPDATE_SUCCESS: 'USER_PARTIAL_UPDATE_SUCCESS'
}

export const home = {
  GET_BOOKING_AND_CHEF_INFO: 'GET_BOOKING_AND_CHEF_INFO'
}
export const chat = {
  SEND_MESSAGE_REQUEST: 'SEND_MESSAGE_REQUEST',
  SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE',
  RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
  INITIALIZE_CHATS: 'INITIALIZE_CHATS',
  DELETE_MESSAGE_REQUEST: 'DELETE_MESSAGE_REQUEST',
  CLEAR_CHAT: 'CLEAR_CHAT',
  LIST_CHATS: 'LIST_CHATS',
}

export const settings = {
  TOGGLE_PUSH_NOTIFICATION: ' TOGGLE_PUSH_NOTIFICATION',
  SET_CURRENCY: 'SET_CURRENCY',
  SET_PAYMENT_METHOD: "SET_PAYMENT_METHOD",
  ENABLE_TEXT_MESSAGES: "ENABLE_TEXT_MESSAGES",
  ENABLE_PHONE_CALLS: "ENABLE_PHONE_CALLS",
  ENABLE_NEWSLETTER: "ENABLE_NEWSLETTER",
  UPDATE_COORDINATES: 'UPDATE_COORDINATES'
}

export const booking = {
  SET_BOOKING_STATUS: 'SET_BOOKING_STATUS',
  GET_ALL_BOOKINGS_REQUEST: 'GET_ALL_BOOKINGS_REQUEST',
  GET_ALL_BOOKINGS_SUCCESS: 'GET_ALL_BOOKINGS_SUCCESS'
}

export const chefInfo = {
  GET_CHEF_INFO_REQUEST: 'GET_CHEF_INFO_REQUEST',
  GET_CHEF_INFO_SUCCESS: 'GET_CHEF_INFO_SUCCESS',
  CHEF_INFO_PARTIAL_UPDATE_REQUEST: 'CHEF_INFO_PARTIAL_UPDATE_REQUEST',
  CHEF_INFO_PARTIAL_UPDATE_SUCCESS: 'CHEF_INFO_PARTIAL_UPDATE_SUCCESS',
  CHEF_INFO_FULL_UPDATE_REQUEST: 'CHEF_INFO_FULL_UPDATE_REQUEST',
  CHEF_INFO_FULL_UPDATE_SUCCESS: 'CHEF_INFO_FULL_UPDATE_SUCCESS'
}

export const cookbook = {
  CREATE_DISH_REQUEST: 'CREATE_DISH_REQUEST',
  CREATE_DISH_SUCCESS: 'CREATE_DISH_SUCCESS',
  UPDATE_DISH_REQUEST: 'UPDATE_DISH_REQUEST',
  UPDATE_DISH_SUCCESS: 'UPDATE_DISH_SUCCESS',
  DELETE_DISH_REQUEST: 'DELETE_DISH_REQUEST',
  DELETE_DISH_SUCCESS: ' DELETE_DISH_REQUEST',
  GET_ALL_DISHES_REQUEST: 'GET_ALL_DISHES_REQUEST',
  GET_ALL_DISHES_SUCCESS: 'GET_ALL_DISHES_SUCCESS',
  SEARCH_DISHES_REQUEST: 'SEARCH_DISHES_REQUEST'
}