export const service = {
  ADD_SERVICE_REQUEST: 'ADD_SERVICE_REQUEST',
  ADD_SERVICE_SUCCESS: 'ADD_SERVICE_SUCCESS',
  REMOVE_SERVICE_REQUEST: 'REMOVE_SERVICE_REQUEST',
  REMOVE_SERVICE_SUCCESS: 'REMOVE_SERVICE_SUCCESS',
  GET_SERVICES: 'GET_SERVICES',
  INITIALIZE_SERVICES: 'INITIALIZE_SERVICES',
}

export const serviceRequest = {
  DECLINE_REQUEST: 'DECLINE_REQUEST',
  ACCEPT_REQUEST: 'ACCEPT_REQUEST'
}

export const auth = {
  SIGN_IN: 'SIGN_IN',
  SIGN_IN_REQUEST: 'SIGNIN_REQUEST',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',
  SIGN_OUT: 'SING_OUT',
  SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
  RESTORE_TOKEN: 'RESTORE_TOKEN',
  RESTORE_TOKEN_REQUEST: 'RESTORE_TOKEN_REQUEST',
  RESTORE_TOKEN_SUCCESS: 'RESTORE_TOKEN_SUCCESS',
  RESTORE_TOKEN_FAILURE: 'RESTORE_TOKEN_FAILURE',
}

export const account = {
  RESTORE_ACCOUNT: ' RESTORE_ACCOUNT'
}

export const chat = {
  SEND_MESSAGE_REQUEST: 'SEND_MESSAGE_REQUEST',
  SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE',
  RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
  INITIALIZE_CHATS: 'INITIALIZE_CHATS',
  DELETE_MESSAGE_REQUEST: 'DELETE_MESSAGE_REQUEST',
  CLEAR_CHAT: 'CLEAR_CHAT',
  LIST_CHATS: 'LIST_CHATS',
}

export const settings = {
  TOGGLE_PUSH_NOTIFICATION: ' TOGGLE_PUSH_NOTIFICATION',
  SET_CURRENCY: 'SET_CURRENCY',
  SET_PAYMENT_METHOD: "SET_PAYMENT_METHOD",
  ENABLE_TEXT_MESSAGES: "ENABLE_TEXT_MESSAGES",
  ENABLE_PHONE_CALLS: "ENABLE_PHONE_CALLS",
  ENABLE_NEWSLETTER: "ENABLE_NEWSLETTER",
  UPDATE_COORDINATES: 'UPDATE_COORDINATES'
}

export const bookings = {
  SET_BOOKING_STATUS: 'SET_BOOKING_STATUS',
  INITIALIZE_BOOKINGS: 'INITIALIZE_BOOKINGS',
}